---
title: Tarjetas Credomatic
timezone: America/Guatemala
collections:
  posts:
    title: Posts
    output: true
  tarjetas:
    title: Tarjetas
    output: true
    permalink: "/tarjetas/:path.html"
    test: hola
  uploads:
    title: Uploads
    output: true
  test:
    title: test
    output: true
    permalink: "/test/:path.html"
    hi: hjhjh
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: tarjetas
  values:
    layout: tarjetas
    tipo: ["Cl√°sica", "Dorada", "Platino", "Black", "Infinite"]
    uso: ["Compras", "Compras Online", "Avance de efectivo", "Compra de Cartera", "Todas"]
    lealtad: ["Millas", "Puntos", "Cashback", "Descuentos", "Otros Beneficios"]
    forma_de_acumulacion:
    otros_beneficios:
    tipo_de_cliente: ["Asalariado", "Independiente", "Ambos"]
    cargo_administrativo:
    anualidad:
    reto_de_facturacion:

email: emenaalt@credomatic.com
description: ''
baseurl: ''
url: http://yourdomain.com
github_username: guayom
markdown: kramdown
permalink: pretty
