---
title: Tarjetas Credomatic
timezone: America/Guatemala
collections:
  posts:
    title: Posts
    output: true
  tarjetas:
    title: Tarjetas
    output: true
    permalink: "/tarjetas/:path.html"
    test: hola
  uploads:
    title: Uploads
    output: true
  test:
    title: test
    output: true
    permalink: "/test/:path.html"
    hi: hjhjh
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: tarjetas
  values:
    layout: tarjetas
    test: testing field
email: emenaalt@credomatic.com
description: ''
baseurl: ''
url: http://yourdomain.com
github_username: guayom
markdown: kramdown
permalink: pretty
