---
title: Tarjetas Credomatic
timezone: America/Guatemala
collections:
  posts:
    title: Posts
    output: true
  tarjetas:
    title: Tarjetas
    output: true
    permalink: "/tarjetas/:path"
    uso:
    - Compras
    - Compras Onine
    - Avance de efectivo
    - Compra de cartera
    - Todas
    testingfield: yeah
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: emenaalt@credomatic.com
description: ''
baseurl: ''
url: http://yourdomain.com
github_username: guayom
markdown: kramdown
permalink: pretty
